
services:
  YUGABYTE-01:
      container_name: YUGABYTE-01
      hostname: YUGABYTE-01
      # image: yugabytedb/yugabyte:latest
      image: yugabytedb/yugabyte:2024.1.3.0-b105
      command: /home/yugabyte/bin/yugabyted start --background=false --base_dir=/home/yugabyte/yb_data
      # command: sleep 365d
      mem_limit: '16Gb'
      volumes:
      - YUGABYTE_01-DATA:/home/yugabyte/yb_data
      - YADAMU_01-SHARED:/mnt/shared
      networks:
      - YADAMU-NET
      ports:
       - "7000:7000"
       - "9010:9000" 
       - "15433:15433"
       - "5533:5433" 
       - "9042:9042"
      
networks: 
  YADAMU-NET:
     name: YADAMU-NET

volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  YUGABYTE_01-DATA:
