
services:
  commandline:
    image: yadamu/commandline:latest
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/linux/commandLine
      # DOCKER_BUILDKIT is enabled by default in Compose V2

  environment:
    image: yadamu/environment:latest
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/linux/environment
      no_cache: true
      args:
        BUILDKIT_PROGRESS: plain

  base:
    image: yadamu/base:latest
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/linux/yadamu

  regression:
    image: yadamu/regression:latest
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/linux/regression

  secure:
    image: yadamu/secure:latest
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/linux/secure

  service:
    image: yadamu/service:latest
    build:
      context: ../../..
      dockerfile: docker/dockerfiles/linux/service
