services:
  SNOWSQL-01:
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
         sql:  ../../../src/sql/snowflake
         conn: ../../../qa/connections
    image: yadamu/snowsql:latest
    container_name: SNOWSQL-01
    hostname: SNOWSQL-01
    networks:
      - yadamu-net
    # Keep container running for interactive use
    command: bash -c "./configure.sh && tail -f /dev/null"

networks:
  yadamu-net: