
services:

  MSSQL17-01:
    container_name: MSSQL17-01
    image:  yadamu/svr-2016/mssql:2017-CU26
    isolation: hyperv
    mem_limit: 6144M
    networks:
      - YADAMU-NET
    ports:
      - "14332:1433"
    environment:
      DELAY: 0
      ACCEPT_EULA: Y
      SA_PASSWORD: oracle#1
    volumes:
      - YADAMU_01-SHARED:c:\mount
      - MSSQL17-01-DATA:C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA
      - MSSQL17-01-LOG:C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\LOG
    restart: always

networks:
  YADAMU-NET:
     name: YADAMU-NET

volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  MSSQL17-01-DATA:
  MSSQL17-01-LOG:
